In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

Numpy advantages:

* numpy arrays are statically typed. Their type is defined when the array is created. Therefore it's easy to use them with compiled languages like C.



In [18]:
# create 1D array (vector) from python list
# Vector variable names small letters.
a = np.array([1,2,3,4])

# create 2D array (matrix) from python list
# dims must be equal in rows and columns
# Matrix variable names Capital letters.
B = np.array([[1,2,3,4], [4,5,6,8]])
B.shape
B[0] # first row
type(B)
B.size # num elements
b.dtype # get the element data type

dtype('int32')

In [20]:
# Create array with data type
M = np.array([[1,2],[3,4]], dtype=float)
M

array([[1., 2.],
       [3., 4.]])

Data Types in arrays:

* int, float, complex, bool, object
* int64, int16, float128, complex128

# Generating arrays

In [39]:
# create a range
x = np.arange(3,8,2) #start, excluding stop, step

# create a linear space
y = np.linspace(1, 2, 10) # start, inc stop, num samples =50
# help(np.linspace)

np.set_printoptions(precision=2, suppress=True)
print(y)

[1.   1.11 1.22 1.33 1.44 1.56 1.67 1.78 1.89 2.  ]


In [51]:
#help(np.logspace)
np.set_printoptions(precision=2, suppress=True)

z = np.logspace(0, 2, 10, base=10)
print(z)

[  1.     1.67   2.78   4.64   7.74  12.92  21.54  35.94  59.95 100.  ]


# Random Data

In [79]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

# standard normal distributed random numbers
np.random.randn(5,5)


array([[ 0.67, -0.87, -1.19,  0.76, -0.75],
       [-1.  , -0.52, -1.19,  2.16,  0.18],
       [ 1.32, -0.41,  0.11, -0.57,  2.03],
       [-0.16,  0.17, -0.44, -0.65,  0.83],
       [-0.97,  0.42, -0.7 ,  0.24, -1.33]])

# Diagonal Matrix

In [83]:
# with shift (offset)
np.diag([1,2,4], k=-3)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0]])

In [92]:
a = np.zeros((4,4), int)
np.fill_diagonal(a, 1)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# CSV Data

In [ ]:
data = np.ge